### PR TITLE
citation

### PR DESCRIPTION
**Pull request by h1alexbel**
## PR-Codex overview
This PR adds metadata information to the `CITATION.cff` file.

### Detailed summary
- Added `cff-version` metadata with value `1.2.0`
- Added `message` metadata with value `"If you use this software, please cite it as below."`
- Added `authors` metadata with `family-names`, `given-names` and `orcid` fields
- Added `title` metadata with value `"EO Kafka Producers and consumers for working with Apache Kafka message broker"`
- Added `version` metadata with value `0.1.3`
- Added `date-released` metadata with value `2023-05-08`
- Added `url` metadata with value `"https://eo-cqrs.github.io/eo-kafka"`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-05-15T14:22:17.813393``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
