### PR TITLE
81

### PR DESCRIPTION
**Pull request by l3r8yJ**
@h1alexbel branch with IT

### CODE REVIEW

**Comment by l3r8yJ** [comment]
closed until #134 is open

**Comment by l3r8yJ** [comment]
@h1alexbel do you see something problematic here? Problem still the same

```java
@Testcontainers
final class SimpleTest {

  @Container
  public final KafkaContainer kafka =
    new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:7.3.0"))
      .withEmbeddedZookeeper();

  @BeforeEach
  void startKafka() {
    this.kafka.start();
  }

  @AfterEach
  void stopKafka() {
    this.kafka.stop();
  }

  @Test
  public void kafkaRunning() {
    MatcherAssert.assertThat(
      "Kafka container running",
      this.kafka.isRunning(),
      Matchers.is(true)
    );
  }

  @Test
  public void pollsDataCorrectly() {
    try (
      final Producer<String, String> producer =
        new KfProducer<>(
          new KfProducerSettings<>(
            new KfProducerParams(
              new KfParams(
                new BootstrapServers(this.kafka.getBootstrapServers()),
                new KeySerializer("org.apache.kafka.common.serialization.StringSerializer"),
                new ValueSerializer("org.apache.kafka.common.serialization.StringSerializer")
              )
            )
          )
        );
      final Consumer<String, String> consumer =
        new KfConsumer<>(
          new KfConsumerSettings<>(
            new KfConsumerParams(
              new KfParams(
                new BootstrapServers(this.kafka.getBootstrapServers()),
                new GroupId("1"),
                new KeyDeserializer("org.apache.kafka.common.serialization.StringDeserializer"),
                new ValueDeserializer("org.apache.kafka.common.serialization.StringDeserializer")
              )
            )
          )
        )
    ) {
      consumer.subscribe(new ListOf<>("test-t"));
      producer.send(
        "my_key",
        new KfData<>("data-from-test-producer", "test-t", 1)
      );
      MatcherAssert.assertThat(
        "Consumes right number of data",
        consumer.iterate("test-t", Duration.ofMillis(0L)),
        Matchers.hasSize(1)
      );
    } catch (final Exception ex) {
      throw new IllegalStateException(ex);
    }
  }
}
```

**Comment by h1alexbel** [comment]
@l3r8yJ the first thing to test manually: producer sends a message in a particular topic, then you connect to the broker via:
```
docker exec --interactive --tty broker \
kafka-console-consumer --bootstrap-server localhost:9092 \
                       --topic {your topic here}
```
and you need to verify that message was delivered

**Comment by h1alexbel** [comment]
@l3r8yJ by the way what `bootstrap.servers` property value do you receive from 
```java
@Container
  public final KafkaContainer kafka =
    new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:7.3.0"))
      .withEmbeddedZookeeper();
```

**Comment by l3r8yJ** [comment]
@h1alexbel `BSERVERS: PLAINTEXT://localhost:61640`

**Comment by h1alexbel** [comment]
@l3r8yJ maybe [this](https://stackoverflow.com/questions/52017749/kafka-docker-and-leader-not-available) will help

**Comment by l3r8yJ** [comment]
that what `kafka.getContainerInfo()` says: 
```log
InspectContainerResponse(args=[-c, #!/bin/bash
echo 'clientPort=2181' > zookeeper.properties
echo 'dataDir=/var/lib/zookeeper/data' >> zookeeper.properties
echo 'dataLogDir=/var/lib/zookeeper/log' >> zookeeper.properties
zookeeper-server-start zookeeper.properties &
echo '' > /etc/confluent/docker/ensure 
/etc/confluent/docker/run 
], config=ContainerConfig(attachStderr=false, attachStdin=false, attachStdout=false, cmd=[sh, -c, #!/bin/bash
echo 'clientPort=2181' > zookeeper.properties
echo 'dataDir=/var/lib/zookeeper/data' >> zookeeper.properties
echo 'dataLogDir=/var/lib/zookeeper/log' >> zookeeper.properties
zookeeper-server-start zookeeper.properties &
echo '' > /etc/confluent/docker/ensure 
/etc/confluent/docker/run 
], domainName=, entrypoint=null, env=[KAFKA_LOG_FLUSH_INTERVAL_MESSAGES=9223372036854775807, KAFKA_BROKER_ID=1, KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1, KAFKA_ADVERTISED_LISTENERS=BROKER://localhost:9092, KAFKA_ZOOKEEPER_CONNECT=localhost:2181, KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=1, KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1, KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093,BROKER://0.0.0.0:9092, KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1, KAFKA_INTER_BROKER_LISTENER_NAME=BROKER, KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT, KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, container=oci, LANG=C.UTF-8, CUB_CLASSPATH="/usr/share/java/cp-base-new/*", COMPONENT=kafka], exposedPorts=[2181/tcp, 9092/tcp, 9093/tcp], hostName=df2563802aeb, image=confluentinc/cp-kafka:7.3.0, labels={architecture=arm64, build-date=2022-09-06T17:24:52.011978, com.redhat.build-host=arm-003.osbs.prod.upshift.rdu2.redhat.com, com.redhat.component=ubi8-minimal-container, com.redhat.license_terms=https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI, description=Common base image for Confluent's Docker images., distribution-scope=public, io.confluent.docker=true, io.confluent.docker.build.number=2, io.confluent.docker.git.id=bed15da0, io.confluent.docker.git.repo=confluentinc/kafka-images, io.k8s.description=The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly., io.k8s.display-name=Red Hat Universal Base Image 8 Minimal, io.openshift.expose-services=, io.openshift.tags=minimal rhel8, maintainer=partner-support@confluent.io, name=cp-kafka, org.testcontainers=true, org.testcontainers.lang=java, org.testcontainers.sessionId=89fa96b4-afa0-4503-9169-803abf828c0e, org.testcontainers.version=1.17.6, release=7.3.0, summary=Confluent platform Kafka., url=https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8-minimal/images/8.6-941, vcs-ref=50293e4ba66ca2194d8ee5a149a665cb9a375c71, vcs-type=git, vendor=Confluent, version=bed15da0}, macAddress=null, networkDisabled=null, onBuild=null, stdinOpen=false, portSpecs=null, stdInOnce=false, tty=false, user=appuser, volumes={/etc/kafka/secrets={}, /var/lib/kafka/data={}}, workingDir=/home/appuser, healthCheck=null), created=2023-03-20T13:02:31.053076048Z, driver=overlay2, execDriver=null, hostConfig=HostConfig(binds=[], blkioWeight=0, blkioWeightDevice=null, blkioDeviceReadBps=null, blkioDeviceWriteBps=null, blkioDeviceReadIOps=null, blkioDeviceWriteIOps=null, memorySwappiness=null, nanoCPUs=0, capAdd=null, capDrop=null, containerIDFile=, cpuPeriod=0, cpuRealtimePeriod=0, cpuRealtimeRuntime=0, cpuShares=0, cpuQuota=0, cpusetCpus=, cpusetMems=, devices=null, deviceCgroupRules=null, deviceRequests=null, diskQuota=null, dns=null, dnsOptions=null, dnsSearch=null, extraHosts=[], groupAdd=null, ipcMode=shareable, cgroup=, links=[], logConfig=LogConfig(type=json-file, config={}), lxcConf=null, memory=0, memorySwap=0, memoryReservation=0, kernelMemory=0, networkMode=default, oomKillDisable=null, init=null, autoRemove=false, oomScoreAdj=0, portBindings={2181/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@59546cfe, 9093/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@29ea78b1}, privileged=false, publishAllPorts=false, readonlyRootfs=false, restartPolicy=no, ulimits=null, cpuCount=0, cpuPercent=0, ioMaximumIOps=0, ioMaximumBandwidth=0, volumesFrom=[], mounts=null, pidMode=, isolation=null, securityOpts=null, storageOpt=null, cgroupParent=, volumeDriver=, shmSize=67108864, pidsLimit=null, runtime=runc, tmpFs=null, utSMode=, usernsMode=, sysctls=null, consoleSize=[0, 0], cgroupnsMode=private), hostnamePath=/var/lib/docker/containers/df2563802aebc27476e68091267941d6ce0a554ff82c952c4b74d51e47c0f3c6/hostname, hostsPath=/var/lib/docker/containers/df2563802aebc27476e68091267941d6ce0a554ff82c952c4b74d51e47c0f3c6/hosts, logPath=/var/lib/docker/containers/df2563802aebc27476e68091267941d6ce0a554ff82c952c4b74d51e47c0f3c6/df2563802aebc27476e68091267941d6ce0a554ff82c952c4b74d51e47c0f3c6-json.log, id=df2563802aebc27476e68091267941d6ce0a554ff82c952c4b74d51e47c0f3c6, sizeRootFs=null, imageId=sha256:1631b40dbeb5ce23c65b1019784cb8d101b2631f4879724c38fa2ada6ce5d086, mountLabel=, name=/frosty_hawking, restartCount=0, networkSettings=NetworkSettings(bridge=, sandboxId=23602dec7fa9f77c9c4711e5cab4e28e54b9608a4d277ed2918946494d62c7c0, hairpinMode=false, linkLocalIPv6Address=, linkLocalIPv6PrefixLen=0, ports={2181/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@2d2acd89, 9092/tcp=null, 9093/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@7baf6acf}, sandboxKey=/var/run/docker/netns/23602dec7fa9, secondaryIPAddresses=null, secondaryIPv6Addresses=null, endpointID=5db0edfecf7b6d98601962bcc9748e0857f5fa56611920c11db753d39f603efa, gateway=172.17.0.1, portMapping=null, globalIPv6Address=, globalIPv6PrefixLen=0, ipAddress=172.17.0.3, ipPrefixLen=16, ipV6Gateway=, macAddress=02:42:ac:11:00:03, networks={bridge=ContainerNetwork(ipamConfig=null, links=[], aliases=null, networkID=692a2c84d47deb4f7908c1b3d7f8b42cda0c7d5aaacb8fd141250da73f24d68b, endpointId=5db0edfecf7b6d98601962bcc9748e0857f5fa56611920c11db753d39f603efa, gateway=172.17.0.1, ipAddress=172.17.0.3, ipPrefixLen=16, ipV6Gateway=, globalIPv6Address=, globalIPv6PrefixLen=0, macAddress=02:42:ac:11:00:03)}), path=sh, processLabel=, resolvConfPath=/var/lib/docker/containers/df2563802aebc27476e68091267941d6ce0a554ff82c952c4b74d51e47c0f3c6/resolv.conf, execIds=null, state=InspectContainerResponse.ContainerState(status=running, running=true, paused=false, restarting=false, oomKilled=false, dead=false, pid=6520, exitCode=0, error=, startedAt=2023-03-20T13:02:31.700082132Z, finishedAt=0001-01-01T00:00:00Z, health=null), volumes=null, volumesRW=null, node=null, mounts=[InspectContainerResponse.Mount(name=1cce6662033ac67a60438c61d8f7da82324a71684ee02b053ec98bdc04fb52f5, source=/var/lib/docker/volumes/1cce6662033ac67a60438c61d8f7da82324a71684ee02b053ec98bdc04fb52f5/_data, destination=/etc/kafka/secrets, driver=local, mode=, rw=true), InspectContainerResponse.Mount(name=25501fcdd0d67f2a01173ff7b9f03d1ced681760a67b59d747d8934b8a2eb0eb, source=/var/lib/docker/volumes/25501fcdd0d67f2a01173ff7b9f03d1ced681760a67b59d747d8934b8a2eb0eb/_data, destination=/var/lib/kafka/data, driver=local, mode=, rw=true)], graphDriver=GraphDriver(name=overlay2, data=GraphData(rootDir=null, deviceId=null, deviceName=null, deviceSize=null, dir=null)), platform=linux)
```

**Pull request closed without merging**
