### PR TITLE
strings enum

### PR DESCRIPTION
**Pull request by l3r8yJ**
@h1alexbel take a look, please

### CODE REVIEW

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
Seems that Rultor is unavailable(

**Comment by l3r8yJ** [comment]
@h1alexbel maybe tomorrow we can do it

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@h1alexbel can you try to merge some test pull request?

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ what is the GHA?

**Comment by l3r8yJ** [comment]
@h1alexbel GitHub Actions

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@h1alexbel [seems](https://github.com/yegor256/rultor/issues/1659#issuecomment-1486535901) to be all right now, let's try it

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ thanks!

**Pull request merged**
