### PR TITLE
test pr

### PR DESCRIPTION
**Pull request by l3r8yJ**
@h1alexbel 
test pr for new image

### CODE REVIEW

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
the same problem: invalid target release.
maybe ```maven``` installed on this image does not support java 17

**Comment by l3r8yJ** [comment]
@h1alexbel i have an idea, give me couple of mins

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ 

```
Maven home: /usr/local/apache-maven/apache-maven-3.8.6
Java version: 11.0.17, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-105-generic", arch: "amd64", family: "unix"
0m0m+ mvn clean install --errors --batch-mode
0m0m[INFO] Error stacktraces are turned on.
```

**Comment by l3r8yJ** [comment]
@h1alexbel i see, here still yegor image

**Comment by h1alexbel** [comment]
> @h1alexbel i see, here still yegor image

Maybe we need build image on top of yegor's?
And just re install Java and Maven?

**Comment by l3r8yJ** [comment]
@h1alexbel i need to check `.rultor', I often make typos in configurations

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@h1alexbel close your eyes and cross your fingers

**Comment by h1alexbel** [comment]
Nooooooo

**Comment by l3r8yJ** [comment]
@h1alexbel I see what the problem is, the image got the `3.6.3` version of maven, I missed again, come back soon

**Comment by h1alexbel** [comment]
https://stackoverflow.com/questions/44438848/maven-crashes-when-trying-to-compile-a-project-error-executing-maven

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ good job

**Comment by l3r8yJ** [comment]
@h1alexbel thanks!

**Pull request merged**
