### PR TITLE
Add better logs

### PR DESCRIPTION
**Pull request by l3r8yJ**
I've added bit better logging inside of container and also refactored the integration test, maybe it's will be helpful for solving #266 

@h1alexbel take a look, please

---

## PR-Codex overview
This PR adds support for SLF4J logging and improves the KafkaContainer usage in the EntryTest class.

### Detailed summary
- Added dependency to support SLF4J logging
- Removed unused container import
- Improved KafkaContainer usage in EntryTest class:
  - Added `@BeforeAll` method to start the container and set `servers` field
  - Changed `KAFKA_CREATE_TOPICS` env variable to create a specific topic
  - Added `withReuse(true)` to reuse the container instance
  - Added `withLogConsumer` to redirect container logs to SLF4J logger

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@l3r8yJ thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-04-26T23:22:16.812543``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ thanks

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
