### PR TITLE
Consumer Unsubscribes

### LINKED ISSUE #288: KfConsumer.java:38: Unsubscribe is not implemented
The puzzle `236-63d4f363` from #236 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/a85fa7fbe333566c209a19c0dd844673ef221534/src/main/java/io/github/eocqrs/kafka/consumer/KfConsumer.java#L38-L38

The puzzle was created by @h1alexbel on 03-May-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #288

---

## PR-Codex overview
This PR adds an `unsubscribe` method to the `Consumer` interface and implements it in the `KfConsumer` and `FkConsumer` classes. It also adds TODOs for implementing `subscribe`, `iterate`, and `close` methods in the `FkConsumer` class.

### Detailed summary
- Adds `unsubscribe` method to `Consumer` interface
- Implements `unsubscribe` method in `KfConsumer` and `FkConsumer`
- Adds TODOs for implementing `subscribe`, `iterate`, and `close` methods in `FkConsumer`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-05-07T11:12:19.867366``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@l3r8yJ take a look, please

**Review by l3r8yJ — APPROVED** [review]
lgtm

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
