### PR TITLE
Java 17 container

### LINKED ISSUE #4: rultor java 17

### PR DESCRIPTION
**Pull request by l3r8yJ**
@h1alexbel take a look, please

### CODE REVIEW

**Comment by l3r8yJ** [comment]
@h1alexbel note

is a very thin container. If we need additional tools, let me know. Because the original container was broken AF. It had to be made thin, also it will merge and release much faster.

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
seems we need merge this manually

**Comment by h1alexbel** [comment]
@l3r8yJ thanks!

**Comment by l3r8yJ** [comment]
@h1alexbel let's do a test merge

**Comment by h1alexbel** [comment]
> @h1alexbel let's do a test merge

go

**Pull request merged**
