### PR TITLE
KfJsonFlexible

### LINKED ISSUE #406: KfJsonFlexible

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #406 

@l3r8yJ take a look, please

---

## PR-Codex overview
This PR adds support for creating Kafka Consumers and Producers using JSON configuration files. 

### Detailed summary
- Added `KfJsonFlexible` class to create custom Consumer and Producer from JSON files
- Updated documentation with instructions on how to use JSON configuration files for Consumers and Producers

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Review by l3r8yJ — CHANGES_REQUESTED** [review]
@h1alexbel I think we need tests with reading and asserting values from json, wdyt?

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-07-10T10:59:05.416805``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
> @h1alexbel I think we need tests with reading and asserting values from json, wdyt?

@l3r8yJ These tests are already created and maintained by emotion, in `JsonXML` object
here, we just transform JSON to XML

**Comment by l3r8yJ** [comment]
> > @h1alexbel I think we need tests with reading and asserting values from json, wdyt?
> 
> @l3r8yJ These tests are already created and maintained by emotion, in `JsonXML` object here, we just transform JSON to XML

@h1alexbel so, has the produced xml been tested?

**Comment by h1alexbel** [comment]
> 
@l3r8yJ 
yes, [here](https://github.com/eo-cqrs/eokson/blob/master/src/test/java/io/github/eocqrs/eokson/JsonXMLTest.java) it is

**Review by l3r8yJ — APPROVED** [review]
@h1alexbel lgtm, then!

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
