### PR TITLE
test impl

### LINKED ISSUE #132: adding new property to `Settings`

### PR DESCRIPTION
**Pull request by l3r8yJ**
theoretically closes #132 
@h1alexbel take a look, please

### CODE REVIEW

**Comment by h1alexbel** [comment]
@l3r8yJ maybe we can create new object on each kafka setting
```java
interface Setting {
String asXml();
}

class BootstrapServers implements Setting {
// 
}
```

**Comment by h1alexbel** [comment]
@l3r8yJ can you explain how this method `asXml` should work?

**Comment by h1alexbel** [comment]
@l3r8yJ how I see the proof:

```
new KfProducerSettings(
    new Settings(
       new BootstrapServers("localhost:9092"),
         new KeySerializer("class name"),
         new ValueSerializer("class name")
  )
)

```

**Comment by l3r8yJ** [comment]
@h1alexbel I thought, indeed, I like your implementation better than what I suggested, but I would change the names a bit
take a look, please

**Review by h1alexbel — APPROVED** [review]
@l3r8yJ cheers!

**Comment by h1alexbel** [comment]
@l3r8yJ by the way we need integrate all this stuff with `KfProducerSettings` and `KfConsumerSettings`

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
> @l3r8yJ by the way we need integrate all this stuff with `KfProducerSettings` and `KfConsumerSettings`

@h1alexbel puzzle suggestion?

**Comment by h1alexbel** [comment]
@l3r8yJ another suggestion: add method `name()` to Attribute interface

e.g. :
```java
class BootstrapServers implements Attribute {

String name () {
return "bootsrap.servers";
}
}
```

**Comment by l3r8yJ** [comment]
@h1alexbel `value()` maybe too:
```java
class BootstrapServers implements Attribute {

String name () {
  return "bootsrap.servers";
}
String value() {
  return this.value;
}
}
```

**Comment by h1alexbel** [comment]
@l3r8yJ looks like getter. Maybe asXml will be better approach

**Comment by l3r8yJ** [comment]
@h1alexbel sure!

**Pull request merged**
