### PR TITLE
Add KfCallback integration test

### LINKED ISSUE #266: KfCallback.java:35-36: Integration test for `KfCallback`...
The puzzle `204-5fca8491` from #204 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/3aa29855a785b99b9631f982795880fde8a4b5d4/src/main/java/io/github/eocqrs/kafka/producer/KfCallback.java#L35-L36

The puzzle was created by @l3r8yJ on 23-Apr-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by l3r8yJ**
closes #266 

@h1alexbel take a look, please

---

## PR-Codex overview
This PR adds a callback mechanism to the Kafka producer and includes an integration test. 

### Detailed summary
- Added `KfCallback` class to implement the callback mechanism for KafkaProducer.
- Added `createsProducerWithCallback` method to `EntryTest` to test the callback mechanism.
- Removed `@todo` comments from `KfCallback` class.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@l3r8yJ thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-04-28T17:12:19.845237``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@l3r8yJ lgtm

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ thanks

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
