### PR TITLE
FkStorage migration to `xfake`

### LINKED ISSUE #339: migrate FkStorage to `xfake`

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #339 

---

## PR-Codex overview
This PR deprecates some classes and interfaces from the `io.github.eocqrs.kafka.fake` package and replaces them with their counterparts from the `io.github.eocqrs.xfake` package. It also moves the affected classes and interfaces from the `io.github.eocqrs.kafka.fake` package to the `io.github.eocqrs.kafka.fake.storage` package.

### Detailed summary
- Deprecated `FkStorage` and `InFile` classes and `InFileTest` test class
- Deprecated `ImmutableReentrantLock` class
- Added `FkStorage`, `InFile`, and `ImmutableReentrantLock` classes from the `io.github.eocqrs.xfake` package
- Added `InXml` class from the `io.github.eocqrs.xfake` package
- Updated `InXmlTest` to use the new `InFile` constructor
- Moved all affected classes and interfaces to the `io.github.eocqrs.kafka.fake.storage` package
- Added license header to `package-info.java` in the `io.github.eocqrs.kafka.fake.storage` package

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-05-28T11:22:21.164233``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@h1alexbel ok, I've removed this task from scope. I'm not managing it anymore.

**Pull request merged**
