### PR TITLE
puzzles, KfXmlFlexible, KfFlexibleEnvelope

### LINKED ISSUE #154: KfFlexible.java:15-16: Opportunity for XML configuration...
The puzzle `147-324191c0` from #147 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/8e722079201fab59308e9e3674d35fa5218e8906/src/main/java/io/github/eocqrs/kafka/parameters/KfFlexible.java#L15-L16

The puzzle was created by Ivan on 21-Mar-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by l3r8yJ**
closes #154 

@h1alexbel take a look, please

### CODE REVIEW

**Comment by l3r8yJ** [comment]
@h1alexbel this one is ready for reviewing

**Review by h1alexbel — APPROVED** [review]
@l3r8yJ interesting implementation, I like it!

**Comment by l3r8yJ** [comment]
@h1alexbel can we merge or do we need to add/fix something?

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ thanks!

**Pull request merged**
