### PR TITLE
formatting

### LINKED ISSUE #424: Fix that
https://github.com/eo-cqrs/eo-kafka/blob/17b598b3cc0c9927d74b40797e4d40e660c5fca4/src/main/java/io/github/eocqrs/kafka/consumer/KfConsumer.java#L79-L83

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #424 

---

## PR-Codex overview
This PR focuses on improving the readability of the `subscribe` method in the `KfConsumer` class. 

### Detailed summary
- The `subscribe` method now has better formatting with the parameters and closing parenthesis each on a new line.
- No functional changes were made, only formatting improvements.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-08-09T07:19:04.653380``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
