### PR TITLE
close producer

### PR DESCRIPTION
**Pull request by l3r8yJ**
@h1alexbel take a look, please

found some bug

### CODE REVIEW

**Comment by h1alexbel** [comment]
@l3r8yJ By the way we need remove this disabled test

**Comment by l3r8yJ** [comment]
@h1alexbel take a look, please

**Comment by h1alexbel** [comment]
@l3r8yJ can you please create `todo` for pdd on `ITCase` for Producer <-> Consumer communication?

**Comment by l3r8yJ** [comment]
@h1alexbel check the puzzle, please

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@l3r8yJ thanks

**Pull request merged**
