### PR TITLE
81 fixed

### PR DESCRIPTION
**Pull request by l3r8yJ**
@h1alexbel here is a fake passing tests

Can you checkout to this branch, enable `docker`, run `mvn clean install -Pintegration-test` and provide me with logs, please?

### CODE REVIEW

**Comment by l3r8yJ** [comment]
well, still same issue with producer

but, when i've run this code
telegram-cloud-photo-size-2-5262778936125933335-y

and getting data from `console producer' passed the test, any producer configurations just don't work as I think it should work

@h1alexbel wdyt

**Comment by h1alexbel** [comment]
@l3r8yJ ok, tomorrow I will provide you with logs

**Comment by h1alexbel** [comment]
@l3r8yJ maybe I know how to fix this issue, by configuring the admin client: https://docs.confluent.io/platform/current/installation/configuration/admin-configs.html#ak-adminclient-configurations-for-cp

**Comment by h1alexbel** [comment]
> well, still same issue with producer
> 
> but, when i've run this code telegram-cloud-photo-size-2-5262778936125933335-y
> 
> and getting data from `console producer` passed the test, any producer configurations just don't work as I think it should work
> 
> @h1alexbel wdyt

@l3r8yJ can I access to this code snippet?

**Comment by h1alexbel** [comment]
@l3r8yJ LEADER NOT AVAILABLE

**Comment by l3r8yJ** [comment]
> > well, still same issue with producer
> > but, when i've run this code telegram-cloud-photo-size-2-5262778936125933335-y
> > and getting data from `console producer` passed the test, any producer configurations just don't work as I think it should work
> > @h1alexbel wdyt
> 
> @l3r8yJ can I access to this code snippet?

@h1alexbel it was in the hello world project, now it's deleted

**Comment by l3r8yJ** [comment]
> @l3r8yJ LEADER NOT AVAILABLE

@h1alexbel need to find how to use it https://docs.confluent.io/platform/current/installation/configuration/admin-configs.html

**Comment by l3r8yJ** [comment]
@h1alexbel take a look, please 

i've added some puzzles, also build pipeline was refactored

**Comment by l3r8yJ** [comment]
@h1alexbel btw, do you have any idea why the changes from the `master` branch are displayed as new?

**Review by h1alexbel — APPROVED** [review]
@l3r8yJ I like it!

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@h1alexbel take a look, please 
 
I disabled integration testing inside `rultor`;
it is to check whether docker containers can be run inside `rultor`

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@h1alexbel removed `linux` trigger, you can try it again

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ thanks!

**Pull request merged**
