### PR TITLE
284

### LINKED ISSUE #284: YamlFlexible

### PR DESCRIPTION
**Pull request by l3r8yJ**
closes #284

---

## PR-Codex overview
This PR focuses on adding YAML configuration support for Kafka producer and consumer settings. 

### Detailed summary
- Added YAML configuration files for producer and consumer settings.
- Added dependencies for SnakeYAML.
- Updated code to read settings from YAML files.
- Added tests for YAML configuration.

> The following files were skipped due to too many changes: `src/test/java/io/github/eocqrs/kafka/yaml/KfYamlConsumerSettingsTest.java`, `src/main/java/io/github/eocqrs/kafka/yaml/KfYamlConsumerSettings.java`, `src/main/java/io/github/eocqrs/kafka/yaml/KfYamlProducerSettings.java`, `src/test/java/io/github/eocqrs/kafka/fake/FkProducerTest.java`, `src/test/java/io/github/eocqrs/kafka/yaml/YamlMapParamsTest.java`, `src/main/java/io/github/eocqrs/kafka/yaml/YamlMapParams.java`, `src/test/java/io/github/eocqrs/kafka/consumer/KfConsumerTest.java`, `src/test/java/io/github/eocqrs/kafka/fake/FkConsumerTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@l3r8yJ thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by l3r8yJ** [comment]
@h1alexbel wdyt

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-07-12T16:29:05.623192``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Review by h1alexbel — CHANGES_REQUESTED** [review]
@l3r8yJ take a look at my comments, please

**Comment by l3r8yJ** [comment]
@h1alexbel fixed

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ great job, thanks!

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
