### PR TITLE
api off from readme

### PR DESCRIPTION
**Pull request by h1alexbel**
### Detailed summary
- Updated kafka-clients.version to 3.5.0
- Removed kafka-streams.version
- Updated cactoos.version to 0.55.0
- Updated lombok.version to 1.18.28
- Updated junit-api.version to 5.9.3
- Renamed "Messages API" section to "Messages"
- Renamed "Producer API" section to "Producers"
- Renamed "Consumer API" section to "Consumers"
- Renamed "Fake API" section to "Fakes"
- Added example with fakes in the "Fakes" section

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-07-04T07:29:05.608557``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
