### PR TITLE
parameters javadocs description

### PR DESCRIPTION
**Pull request by h1alexbel**
## PR-Codex overview
This PR adds documentation to Kafka attribute wrappers in the code. 

### Detailed summary
- Added documentation for `client.rack`, `batch.size`, `client.id`, `linger.ms`, `bootstrap.servers`, `auto.offset.reset`, and `acks` Kafka attributes.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-06-01T09:42:20.000568``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@h1alexbel ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by h1alexbel** [comment]
@rultor merge

**Pull request merged**
