### PR TITLE
settings

### PR DESCRIPTION
**Pull request by h1alexbel**

### CODE REVIEW

**Comment by h1alexbel** [comment]
@l3r8yJ take a look please. maybe you have some ideas how we can integrate these properties with current `KfConsumer/ProducerSettings`

**Comment by l3r8yJ** [comment]
@h1alexbel okay, bit later

**Comment by l3r8yJ** [comment]
@h1alexbel i noticed 1 thing:
in the `asXml()` methods you write the name of the xml tag in camel case, i.e:
`groupId`.
but when you call the `name()` method you write it as `group.id` can you explain why you do that?

**Comment by h1alexbel** [comment]
@l3r8yJ the second one for Kafka. It's pre-configured property name

**Pull request closed without merging**
