### PR TITLE
244

### PR DESCRIPTION
**Pull request by NikiTuz18**
Waiting for the review

### CODE REVIEW

**Comment by zoeself** [comment]
@NikiTuz18 thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-04-12T09:20:12.315031``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@NikiTuz18 
```
Error:  src/main/java/io/github/eocqrs/kafka/fake/FkConsumer.java:[44] (javadoc) JavadocType: Missing a Javadoc comment.
Error:  src/main/java/io/github/eocqrs/kafka/fake/FkProducer.java:[40] (javadoc) JavadocType: Missing a Javadoc comment.
```

**Comment by NikiTuz18** [comment]
> 

There are no errors without comments with todo tags, but I did not remove them, since you asked. Therefore, the pull request was sent along with them

**Comment by l3r8yJ** [comment]
@NikiTuz18 take a look, please at [this](https://github.com/eo-cqrs/eo-kafka/issues/244#issuecomment-1501053843)

**Comment by NikiTuz18** [comment]
I have provided comments to the specified syntax, but it did not help to fix the errors. The only option I see at the moment is deleting comments with todo tags, sorry

photo_2023-04-09_13-02-45
photo_2023-04-09_13-02-47
photo_2023-04-09_13-02-49

**Comment by h1alexbel** [comment]
@NikiTuz18 todo tag is the comment, not a javadoc

**Comment by l3r8yJ** [comment]
@NikiTuz18 please do not use screenshots in such cases use code blocks that begin and end with the \``` symbol

**Comment by NikiTuz18** [comment]
> please do not use screenshots in such cases use code blocks that begin and end with the ``` symbol

Ohh, okey, I'm sorry

**Comment by NikiTuz18** [comment]
@h1alexbel reminder

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@NikiTuz18 thanks!

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
